name: Update Assets from Olive June Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest release tag
        id: get_tag
        run: |
          TAG=$(gh release list --repo CollinDietz/olive-june-gel-collection-scraper --limit 1 --json tagName -q '.[0].tagName')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download latest release tar
        run: |
          mkdir -p tmp
          gh release download --repo CollinDietz/olive-june-gel-collection-scraper \
            --pattern "*.tar.gz" \
            --output tmp/assets.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract assets
        run: |
          rm -rf assets
          tar -xzf tmp/assets.tar.gz

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add assets
          git commit -m "Update assets from olive-june-gel-collection-scraper ${{ steps.get_tag.outputs.tag }}" || echo "No changes to commit."
          git push origin HEAD:${{ github.ref_name }}

      - name: Trigger deploy workflow
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          gh workflow run deploy.yml --ref main
